/**
 * The six capability practices.
 *
 * Replaces the six services on the live site. AI Powered Solutions and
 * Business Automation are merged (both claimed "Workflow Automation");
 * Data & BI is promoted from a bullet to a practice.
 * See docs/architecture/01-strategy-and-positioning.md.
 */

import type { Practice } from "@/types/content";

export const practices: Practice[] = [
  {
    id: "search-ai-visibility",
    index: "01",
    slug: "search-ai-visibility",
    title: "Search & AI Visibility",
    menuDescription: "Get found on Google and in AI answers",
    answer:
      "Search and AI visibility is the work of making a business findable wherever buyers now look — traditional search results, AI Overviews, and the answers generated by ChatGPT, Perplexity and Gemini. It combines technical SEO, content structure and entity clarity into one programme.",
    seo: {
      title: "Search & AI Visibility",
      description:
        "Get found on Google and in AI answers. Technical SEO, AEO, GEO and entity optimisation, delivered as one programme.",
      primaryTopic: "search and AI visibility",
      secondaryTopics: ["SEO", "AEO", "GEO", "AI search optimisation"],
      intent: "commercial",
    },
    audience: ["A3", "A4", "A1", "A2"],
    phase: "P1",
    cta: {
      label: "Request an AI visibility assessment",
      href: "/contact/",
      tier: "T3",
      note: "We measure where you appear today, and where you don't.",
    },
    services: [
      "seo",
      "ai-search-optimisation",
      "technical-seo",
      "answer-engine-optimisation",
      "generative-engine-optimisation",
      "ai-optimisation",
      "search-experience-optimisation",
      "google-business-profile",
    ],
    process: [
      {
        index: 1,
        title: "Measure what exists",
        description:
          "Crawl, index and entity audit, plus a fixed prompt set run against the major AI systems to establish a real baseline.",
        duration: "Weeks 1–2",
      },
      {
        index: 2,
        title: "Fix the structure",
        description:
          "Technical debt, information architecture, schema and crawlability — the constraints that cap everything else.",
        duration: "Weeks 3–6",
      },
      {
        index: 3,
        title: "Build the answers",
        description:
          "Content shaped for extraction and citation, mapped to the queries your buyers actually use.",
        duration: "Weeks 6–12",
      },
      {
        index: 4,
        title: "Measure and iterate",
        description:
          "Rankings, citations and enquiries tracked together. The same prompt set re-run monthly.",
        duration: "Ongoing",
      },
    ],
    faqs: [
      {
        question: "How is AI search optimisation different from SEO?",
        answer:
          "SEO optimises for a ranked list of links. AI search optimisation targets being used as the source inside a generated answer, which rewards clear structure, extractable definitions, and an unambiguous entity. The foundations overlap; the content shape does not.",
      },
      {
        question: "How long before we see results?",
        answer:
          "Technical fixes can show within weeks. Meaningful ranking and citation movement typically starts around week 10 to 12. Anyone promising faster is describing a different, shorter-lived tactic.",
      },
    ],
  },
  {
    id: "digital-marketing",
    index: "02",
    slug: "digital-marketing",
    title: "Digital Marketing & Growth",
    menuDescription: "Build and convert demand",
    answer:
      "Digital marketing and growth covers the demand side of the business: strategy, paid and organic acquisition, content, and the conversion work that turns traffic into enquiries you can actually trace back to revenue.",
    seo: {
      title: "Digital Marketing & Growth",
      description:
        "Performance marketing, content, conversion optimisation and growth strategy — measured against enquiries, not impressions.",
      primaryTopic: "digital marketing and growth",
      secondaryTopics: ["performance marketing", "conversion optimisation"],
      intent: "commercial",
    },
    audience: ["A3", "A5", "A1"],
    phase: "P1",
    cta: {
      label: "Talk to a strategist",
      href: "/contact/",
      tier: "T4",
      note: "30 minutes. We'll tell you where the gaps are.",
    },
    services: [
      "digital-strategy",
      "performance-marketing",
      "conversion-rate-optimization",
    ],
    process: [
      {
        index: 1,
        title: "Find the actual constraint",
        description:
          "Whether the shortfall is arrivals, conversion or follow-up. These look identical in a monthly enquiry figure and need entirely different work, so guessing here costs the quarter.",
      },
      {
        index: 2,
        title: "Fix the measurement",
        description:
          "Enquiry source carried through to the CRM, and outcomes returned from sales. Without that loop, channel decisions get made on last-click and the activity that starts conversations is the first to be defunded.",
      },
      {
        index: 3,
        title: "Work the constraint",
        description:
          "Demand, conversion or follow-up — one at a time, so the effect is attributable. Running all three at once produces a change nobody can explain afterwards.",
      },
      {
        index: 4,
        title: "Report against a hypothesis",
        description:
          "What was believed to be limiting performance, what was done, and whether the measure moved. A report that cannot say a hypothesis was wrong will keep funding it.",
      },
    ],
    faqs: [
      {
        question: "How quickly should we expect results?",
        answer:
          "Paid channels produce usable data within weeks. Organic and content work takes two to three quarters before it contributes meaningfully, and compounds after that. Anyone promising organic results in weeks is describing something else.",
      },
      {
        question: "Should we fix the site or drive more traffic?",
        answer:
          "Usually the site first, where conversion is the weaker link. Sending more people to a page that does not convert raises spend proportionally and changes nothing about the outcome.",
      },
    ],
  },
  {
    id: "web-development",
    index: "03",
    slug: "web-development",
    title: "Websites & Digital Experience",
    menuDescription: "Sites that are found and convert",
    answer:
      "Website design and development for businesses that need a site to do commercial work — be discoverable, load fast, explain something complicated clearly, and turn visitors into enquiries.",
    seo: {
      title: "Websites & Digital Experience",
      description:
        "Corporate websites, e-commerce, web applications and redesigns built for discoverability, speed and conversion.",
      primaryTopic: "website design and development",
      secondaryTopics: ["web design", "corporate websites", "e-commerce"],
      intent: "commercial",
    },
    audience: ["A1", "A3", "A7"],
    phase: "P1",
    cta: {
      label: "Discuss your project",
      href: "/contact/",
      tier: "T4",
    },
    services: [
      "corporate-websites",
      "ui-ux-design",
      "website-redesign",
      "website-performance",
    ],
    process: [
      {
        index: 1,
        title: "Establish what already works",
        description:
          "Which pages earn traffic and enquiries today, and what must not be lost. Redesigns that skip this routinely discard the pages doing the commercial work.",
      },
      {
        index: 2,
        title: "Structure before design",
        description:
          "Hierarchy organised around buyer tasks rather than the org chart. Structure decides what gets found, and it is far cheaper to settle before anything is drawn.",
      },
      {
        index: 3,
        title: "Design and build together",
        description:
          "Server-rendered, accessible and fast as a starting condition rather than a retrofit. Performance and accessibility added at the end cost several times more and achieve less.",
      },
      {
        index: 4,
        title: "Launch without losing visibility",
        description:
          "URL mapping, content parity and rendering parity verified before launch, then monitored across the recovery window rather than the first week.",
      },
    ],
    faqs: [
      {
        question: "How long does a website project take?",
        answer:
          "Eight to fourteen weeks for most business sites, and content readiness is the usual constraint rather than build time. Projects that slip almost always slip waiting for copy and approvals.",
      },
      {
        question: "Will a redesign affect our search visibility?",
        answer:
          "It can, in either direction. Handled properly — URLs mapped, content depth preserved, rendering unchanged — a redesign is neutral to positive. Handled as a launch-week task, it is where most avoidable traffic loss comes from.",
      },
    ],
  },
  {
    id: "software-development",
    index: "04",
    slug: "software-development",
    title: "Software & Product Engineering",
    menuDescription: "Build what you can't buy",
    answer:
      "Custom software engineering for processes that off-the-shelf tools don't fit — internal systems, customer portals, web and mobile applications, and integrations between systems that were never designed to talk to each other.",
    seo: {
      title: "Software & Product Engineering",
      description:
        "Custom software, web and mobile applications, APIs and systems integration — engineered to be maintainable by your own team.",
      primaryTopic: "software and product engineering",
      secondaryTopics: ["web applications", "systems integration", "APIs"],
      intent: "commercial",
    },
    audience: ["A7", "A2", "A8"],
    phase: "P1",
    cta: {
      label: "Technical discovery call",
      href: "/contact/",
      tier: "T4",
      note: "Engineer to engineer, not a sales qualifier.",
    },
    services: [
      "custom-software",
      "web-applications",
      "systems-integration",
    ],
    process: [
      {
        index: 1,
        title: "Understand the process first",
        description:
          "The real one, including the steps that happen off-system. Building against the documented process is the most common reason software is delivered and then worked around.",
      },
      {
        index: 2,
        title: "Specify behaviour, not screens",
        description:
          "What must happen, under which conditions, with what result — including the unhappy paths. Most cost overrun lives in cases the requirements never mentioned.",
      },
      {
        index: 3,
        title: "Build in increments people can use",
        description:
          "One complete workflow at a time, released to real users. Requirements written before anyone has used a working version are the least reliable input available.",
      },
      {
        index: 4,
        title: "Hand over something maintainable",
        description:
          "Documented, tested, and built on choices your own team can hire for. Software nobody but us can change is a liability we have sold you.",
      },
    ],
    faqs: [
      {
        question: "Should we build or buy?",
        answer:
          "Buy wherever the process is genuinely standard, because a product carries maintenance you do not pay for. Build where the process is a real differentiator, or where every available product would need enough configuration to cost more than software would.",
      },
      {
        question: "How do we avoid being locked in to a supplier?",
        answer:
          "Own the repository and the infrastructure accounts from the first day, insist on mainstream technology choices, and require documentation as a deliverable rather than a favour. Lock-in is usually a contracting failure rather than a technical one.",
      },
    ],
  },
  {
    id: "ai-automation",
    index: "05",
    slug: "ai-automation",
    title: "AI & Automation",
    menuDescription: "Remove manual work",
    answer:
      "AI and automation applied to specific business processes — support, sales follow-up, back-office data work — with a clear boundary around what the system handles and what stays with a person.",
    seo: {
      title: "AI & Automation",
      description:
        "AI agents, chatbots, workflow automation and process digitisation — scoped around the work you actually want removed.",
      primaryTopic: "AI and business automation",
      secondaryTopics: ["AI agents", "workflow automation", "AI chatbots"],
      intent: "commercial",
    },
    audience: ["A6", "A7", "A2", "A5"],
    phase: "P1",
    cta: {
      label: "Request an automation assessment",
      href: "/contact/",
      tier: "T3",
      note: "We map the process and the risk before anything is built.",
    },
    services: [
      "ai-agents",
      "ai-chatbots",
      "workflow-automation",
      "sales-automation",
      "ai-consulting",
    ],
    process: [
      {
        index: 1,
        title: "Find the task, not the technology",
        description:
          "Start from work being done repeatedly, with its volume and error cost observed rather than estimated. A project that starts from a platform choice has skipped the part that decides whether it is worth doing.",
      },
      {
        index: 2,
        title: "Test feasibility honestly",
        description:
          "Whether the data and documentation a system would need actually exist and are accurate. This is where a fair number of proposals should stop, and saying so is the value.",
      },
      {
        index: 3,
        title: "Simplify before building",
        description:
          "Remove the steps that no longer have a reason to exist. This regularly returns more than the automation will, and it always reduces what has to be built and maintained.",
      },
      {
        index: 4,
        title: "Build one process end to end",
        description:
          "In production, with the exception path and failure behaviour designed in — not three in parallel, which discovers the same wrong assumption three times at triple the cost.",
      },
      {
        index: 5,
        title: "Hand over with an owner",
        description:
          "Documentation, alerting that reaches a person, and a named owner. Automations without one drift as systems change and credentials rotate, then quietly stop working.",
      },
    ],
    faqs: [
      {
        question: "Where should a first AI or automation project start?",
        answer:
          "With a high-frequency, low-judgement task where the cost of an error is recoverable. That combination is where these systems are reliable and where the recovered time is large enough to be worth measuring.",
      },
      {
        question: "What should not be automated?",
        answer:
          "Work whose value is the judgement in it, anything irreversible without a human check, and processes about to change anyway. Automating an unstable process fixes it in place at exactly the wrong moment.",
      },
    ],
  },
  {
    id: "data-analytics",
    index: "06",
    slug: "data-analytics",
    title: "Data & Business Intelligence",
    menuDescription: "Decisions from your own data",
    answer:
      "Bringing business data into one place and making it usable — reliable tracking, connected systems, and reporting that answers the questions leadership actually asks.",
    seo: {
      title: "Data & Business Intelligence",
      description:
        "Business intelligence, dashboards, analytics implementation and data integration for businesses running on disconnected tools.",
      primaryTopic: "business intelligence and data",
      secondaryTopics: ["dashboards", "analytics implementation"],
      intent: "commercial",
    },
    audience: ["A2", "A7", "A3"],
    phase: "P2",
    cta: {
      label: "Request an assessment",
      href: "/contact/",
      tier: "T3",
    },
    services: [
      "business-intelligence",
      "analytics-implementation",
    ],
    process: [
      {
        index: 1,
        title: "Agree what each number means",
        description:
          "Definitions before dashboards. Most disputes about figures turn out to be two teams applying different, individually reasonable rules to the same question.",
      },
      {
        index: 2,
        title: "Assess the sources",
        description:
          "Which systems hold the data, how reliable each one is, and which gaps have to close before anything built on them can be trusted.",
      },
      {
        index: 3,
        title: "Automate the assembly",
        description:
          "Pipelines with a refresh schedule and failure alerting, so reporting stops being a monthly manual exercise that is already out of date when it lands.",
      },
      {
        index: 4,
        title: "Build for decisions",
        description:
          "Each dashboard supports a specific recurring decision and has an owner. Reporting with no decision attached goes unopened and dilutes attention from the reporting that matters.",
      },
    ],
    faqs: [
      {
        question: "Why do our reports disagree with each other?",
        answer:
          "Almost always because the underlying definitions differ — a different date field, a different exclusion, a different treatment of cancellations. It is a business agreement problem, and no tool resolves it.",
      },
      {
        question: "Do we need a data warehouse?",
        answer:
          "Only when reporting genuinely needs data from several systems at once. A single well-instrumented source answers more questions than most organisations expect, at a fraction of the cost of a platform build.",
      },
    ],
  },
];

export function getPractice(slug: string): Practice | undefined {
  return practices.find((p) => p.slug === slug);
}
