/**
 * The six capability practices.
 *
 * Replaces the six services on the live site. AI Powered Solutions and
 * Business Automation are merged (both claimed "Workflow Automation");
 * Data & BI is promoted from a bullet to a practice.
 * See docs/architecture/01-strategy-and-positioning.md.
 */

import type { Practice } from "@/types/content";

export const practices: Practice[] = [
  {
    id: "search-ai-visibility",
    index: "01",
    slug: "search-ai-visibility",
    title: "Search & AI Visibility",
    menuDescription: "Get found on Google and in AI answers",
    answer:
      "Search and AI visibility is the work of making a business findable wherever buyers now look — traditional search results, AI Overviews, and the answers generated by ChatGPT, Perplexity and Gemini. It combines technical SEO, content structure and entity clarity into one programme.",
    sections: [
      {
        heading: "What changed, and why rankings stopped being the whole story",
        body: [
          "For twenty years, being found meant one thing: appearing high in a list of ten blue links. The mechanism was stable enough that an entire industry organised itself around a single metric. That arrangement is now breaking in a specific, measurable way — the query still happens, the result still ranks, and the click does not arrive, because an answer was assembled above it from sources the searcher never had to visit.",
          "This is not the death of search. It is a change in what winning looks like. A business can hold position three for a term and lose most of its traffic on it, while a competitor that never ranked at all gets named inside the summary. The two outcomes are produced by different mechanisms, and optimising harder for the first does nothing for the second.",
          "The practical consequence is that visibility now has to be measured on more than one surface. A report that shows rankings and organic sessions describes a shrinking part of the picture, and a business reading only that report will conclude things are fine right up until the quarter they are not.",
        ],
      },
      {
        heading: "Five surfaces, five different mechanisms",
        body: [
          "SEO, AEO, GEO, AIO and SXO get treated as fashionable relabelling of the same work. They are not. Each names a genuinely different retrieval mechanism, and a business can be strong on one while being completely absent from the next.",
          "Understanding which mechanism is failing is most of the diagnosis. A site that is technically sound and ranks well but never gets cited in AI answers has a content-shape problem, not a crawl problem. A site AI crawlers cannot render has a foundational problem, and no amount of content work above it will register.",
        ],
        points: [
          "Ranked results reward technical health, relevance and authority — position determines whether anyone sees you.",
          "Direct answers reward a complete answer stated early, in language that survives being lifted out of its page.",
          "Generative answers reward an unambiguous entity, checkable claims, and content a model can attribute with confidence.",
          "Machine readability sits underneath all of it: server-rendered HTML, structured data anchored to one entity, deliberate crawler access.",
          "Post-click experience decides whether the visibility you win converts into anything — being found is not being chosen.",
        ],
      },
      {
        heading: "Where visibility programmes usually go wrong",
        body: [
          "The most common failure is sequencing. Content is commissioned before the technical constraints capping the site have been found, so good work is published onto pages that cannot be crawled properly, and the programme reports activity rather than movement.",
          "The second is entity ambiguity. If a business appears under three slightly different names, with inconsistent details across its own site, its profiles and third-party directories, a language model has no confident thing to attribute a claim to. It will reach for a competitor it can identify cleanly instead. This is invisible in a rankings report and decisive in a generated answer.",
          "The third is measuring only what is easy. Rankings and sessions are available in every tool. Whether you are being cited, and for which questions, is not — it has to be established deliberately, by running a fixed set of prompts against the major systems and recording what comes back.",
        ],
      },
      {
        heading: "How we approach it",
        body: [
          "We start by establishing a baseline that covers all five surfaces, not one. That means a crawl and index audit, an entity audit across the properties that describe your business, and a fixed prompt set run against the major AI systems so there is a real record of where you are named today and where you are not.",
          "Structural work comes before content work, because the structural constraints are what cap everything else. Only once a site can be crawled, rendered and understood does producing more of it become worth the money.",
          "Reporting keeps rankings, citations and enquiries in the same view. Rankings alone will tell you a flattering story in a year when clicks are falling industry-wide; enquiries alone will not tell you why. Read together, they say which surface is working and which needs attention.",
        ],
      },
    ],
    seo: {
      title: "Search & AI Visibility",
      description:
        "Get found on Google and in AI answers. Technical SEO, AEO, GEO and entity optimisation, delivered as one programme.",
      primaryTopic: "search and AI visibility",
      secondaryTopics: ["SEO", "AEO", "GEO", "AI search optimisation"],
      intent: "commercial",
    },
    audience: ["A3", "A4", "A1", "A2"],
    phase: "P1",
    cta: {
      label: "Request an AI visibility assessment",
      href: "/contact/",
      tier: "T3",
      note: "We measure where you appear today, and where you don't.",
    },
    services: [
      "seo",
      "ai-search-optimisation",
      "technical-seo",
      "answer-engine-optimisation",
      "generative-engine-optimisation",
      "ai-optimisation",
      "search-experience-optimisation",
      "google-business-profile",
    ],
    process: [
      {
        index: 1,
        title: "Measure what exists",
        description:
          "Crawl, index and entity audit, plus a fixed prompt set run against the major AI systems to establish a real baseline.",
        duration: "Weeks 1–2",
      },
      {
        index: 2,
        title: "Fix the structure",
        description:
          "Technical debt, information architecture, schema and crawlability — the constraints that cap everything else.",
        duration: "Weeks 3–6",
      },
      {
        index: 3,
        title: "Build the answers",
        description:
          "Content shaped for extraction and citation, mapped to the queries your buyers actually use.",
        duration: "Weeks 6–12",
      },
      {
        index: 4,
        title: "Measure and iterate",
        description:
          "Rankings, citations and enquiries tracked together. The same prompt set re-run monthly.",
        duration: "Ongoing",
      },
    ],
    faqs: [
      {
        question: "How is AI search optimisation different from SEO?",
        answer:
          "SEO optimises for a ranked list of links. AI search optimisation targets being used as the source inside a generated answer, which rewards clear structure, extractable definitions, and an unambiguous entity. The foundations overlap; the content shape does not.",
      },
      {
        question: "How long before we see results?",
        answer:
          "Technical fixes can show within weeks. Meaningful ranking and citation movement typically starts around week 10 to 12. Anyone promising faster is describing a different, shorter-lived tactic.",
      },
    ],
  },
  {
    id: "digital-marketing",
    index: "02",
    slug: "digital-marketing",
    title: "Digital Marketing & Growth",
    menuDescription: "Build and convert demand",
    answer:
      "Digital marketing and growth covers the demand side of the business: strategy, paid and organic acquisition, content, and the conversion work that turns traffic into enquiries you can actually trace back to revenue.",
    sections: [
      {
        heading: "The question most marketing budgets cannot answer",
        body: [
          "Ask a business which half of its marketing spend is working and you will usually get a confident answer about channels and a vague one about revenue. The channel numbers are real — impressions, clicks, cost per lead — but they stop at the point where a lead becomes a conversation, and the conversation is where the money is.",
          "The gap is rarely caused by bad marketing. It is caused by a measurement chain that breaks somewhere between the ad platform, the website, the form, the inbox and the CRM. Each link works. The chain does not, so nobody can trace an enquiry back to the thing that produced it, and every budget decision after that is a preference dressed as a judgement.",
          "Fixing that chain is unglamorous and it is usually the highest-return work available, because it changes the quality of every subsequent decision rather than adding one more campaign to an unmeasured pile.",
        ],
      },
      {
        heading: "Demand you capture and demand you create",
        body: [
          "These are different jobs and they fail for different reasons, but they are routinely funded from one line and judged by one number.",
          "Captured demand is people already looking for what you sell. The work is being present at the moment of search, being credible when they arrive, and making the next step obvious. It converts well because the intent already exists, and it is capped — you cannot capture more demand than the market is currently expressing.",
          "Created demand is people who do not yet know the problem is solvable. The work is education, positioning and repetition, and it looks inefficient on a last-click report because the payoff shows up weeks later somewhere the report is not looking. A business that funds only captured demand hits a ceiling and cannot see why.",
        ],
      },
      {
        heading: "Why channel-first planning goes wrong",
        body: [
          "Most plans start with a channel — we should be doing more on LinkedIn, we should try paid search — rather than with the constraint actually holding growth back. That produces activity in the wrong place: more traffic to a site that does not convert, or better conversion on a page nobody can find.",
          "The more useful sequence is to find the binding constraint first. If enquiries are flat because nobody arrives, the work is acquisition. If plenty arrive and few convert, more acquisition spend makes the problem more expensive rather than smaller. If enquiries arrive and go cold, the constraint is not marketing at all — it is what happens after the form is submitted, which is an operations problem wearing a marketing costume.",
        ],
      },
    ],
    seo: {
      title: "Digital Marketing & Growth",
      description:
        "Performance marketing, content, conversion optimisation and growth strategy — measured against enquiries, not impressions.",
      primaryTopic: "digital marketing and growth",
      secondaryTopics: ["performance marketing", "conversion optimisation"],
      intent: "commercial",
    },
    audience: ["A3", "A5", "A1"],
    phase: "P1",
    cta: {
      label: "Talk to a strategist",
      href: "/contact/",
      tier: "T4",
      note: "30 minutes. We'll tell you where the gaps are.",
    },
    services: [
      "digital-strategy",
      "performance-marketing",
      "conversion-rate-optimization",
    ],
    process: [
      {
        index: 1,
        title: "Find the actual constraint",
        description:
          "Whether the shortfall is arrivals, conversion or follow-up. These look identical in a monthly enquiry figure and need entirely different work, so guessing here costs the quarter.",
      },
      {
        index: 2,
        title: "Fix the measurement",
        description:
          "Enquiry source carried through to the CRM, and outcomes returned from sales. Without that loop, channel decisions get made on last-click and the activity that starts conversations is the first to be defunded.",
      },
      {
        index: 3,
        title: "Work the constraint",
        description:
          "Demand, conversion or follow-up — one at a time, so the effect is attributable. Running all three at once produces a change nobody can explain afterwards.",
      },
      {
        index: 4,
        title: "Report against a hypothesis",
        description:
          "What was believed to be limiting performance, what was done, and whether the measure moved. A report that cannot say a hypothesis was wrong will keep funding it.",
      },
    ],
    faqs: [
      {
        question: "How quickly should we expect results?",
        answer:
          "Paid channels produce usable data within weeks. Organic and content work takes two to three quarters before it contributes meaningfully, and compounds after that. Anyone promising organic results in weeks is describing something else.",
      },
      {
        question: "Should we fix the site or drive more traffic?",
        answer:
          "Usually the site first, where conversion is the weaker link. Sending more people to a page that does not convert raises spend proportionally and changes nothing about the outcome.",
      },
    ],
  },
  {
    id: "web-development",
    index: "03",
    slug: "web-development",
    title: "Websites & Digital Experience",
    menuDescription: "Sites that are found and convert",
    answer:
      "Website design and development for businesses that need a site to do commercial work — be discoverable, load fast, explain something complicated clearly, and turn visitors into enquiries.",
    sections: [
      {
        heading: "A website is a commercial instrument, not a brochure",
        body: [
          "Most website projects are scoped as design projects. Pages are agreed, a look is approved, the thing is built, and everyone moves on. The site then spends the next four years as the single most-visited thing the business owns, quietly deciding whether people who have already found you take the next step.",
          "That framing matters because it changes what counts as done. A brochure is finished when it looks right. A commercial instrument is finished when it can be found, understood and acted on — and those three are testable, which means they can be got wrong in ways an approval meeting will not catch.",
          "The most expensive version of this mistake is a redesign that loses traffic. The design is not usually the cause. The migration is: changed URLs with no mapping, missing redirects, a template that no longer renders content server-side. The site looks better and performs worse, and the two facts feel unrelated to everyone involved.",
        ],
      },
      {
        heading: "Four things decide whether a site performs",
        body: [
          "Almost every underperforming site we look at is failing at one of four things, and it is worth knowing which before commissioning any work — because the fix for each is different and they are not interchangeable.",
        ],
        points: [
          "Discoverability — whether search engines and AI systems can reach, render and understand the pages at all.",
          "Speed and stability — whether the page is usable quickly on the connection and device the visitor actually has.",
          "Clarity — whether a capable but unfamiliar reader can tell what you do, who it is for, and why you rather than someone else.",
          "Conversion path — whether the next step is obvious, low-friction and appropriate to how ready that visitor is.",
        ],
      },
      {
        heading: "Rebuild or repair",
        body: [
          "Not every site needs replacing, and replacing one that did not need it is how a business spends a large budget to arrive back where it started. The honest test is whether the constraints are in the content and configuration, or in the foundation.",
          "Content, structure, speed and conversion problems are usually repairable on the existing platform, often for a fraction of a rebuild. Platform problems are not: if the stack cannot render server-side, cannot support the URL structure the business needs, or cannot be edited without a developer for routine changes, the constraint is structural and repairs will keep hitting the same wall.",
          "We will tell you which of those you have before anyone talks about scope. It is the one judgement that determines whether the rest of the money is well spent.",
        ],
      },
    ],
    seo: {
      title: "Websites & Digital Experience",
      description:
        "Corporate websites, e-commerce, web applications and redesigns built for discoverability, speed and conversion.",
      primaryTopic: "website design and development",
      secondaryTopics: ["web design", "corporate websites", "e-commerce"],
      intent: "commercial",
    },
    audience: ["A1", "A3", "A7"],
    phase: "P1",
    cta: {
      label: "Discuss your project",
      href: "/contact/",
      tier: "T4",
    },
    services: [
      "corporate-websites",
      "ui-ux-design",
      "website-redesign",
      "website-performance",
    ],
    process: [
      {
        index: 1,
        title: "Establish what already works",
        description:
          "Which pages earn traffic and enquiries today, and what must not be lost. Redesigns that skip this routinely discard the pages doing the commercial work.",
      },
      {
        index: 2,
        title: "Structure before design",
        description:
          "Hierarchy organised around buyer tasks rather than the org chart. Structure decides what gets found, and it is far cheaper to settle before anything is drawn.",
      },
      {
        index: 3,
        title: "Design and build together",
        description:
          "Server-rendered, accessible and fast as a starting condition rather than a retrofit. Performance and accessibility added at the end cost several times more and achieve less.",
      },
      {
        index: 4,
        title: "Launch without losing visibility",
        description:
          "URL mapping, content parity and rendering parity verified before launch, then monitored across the recovery window rather than the first week.",
      },
    ],
    faqs: [
      {
        question: "How long does a website project take?",
        answer:
          "Eight to fourteen weeks for most business sites, and content readiness is the usual constraint rather than build time. Projects that slip almost always slip waiting for copy and approvals.",
      },
      {
        question: "Will a redesign affect our search visibility?",
        answer:
          "It can, in either direction. Handled properly — URLs mapped, content depth preserved, rendering unchanged — a redesign is neutral to positive. Handled as a launch-week task, it is where most avoidable traffic loss comes from.",
      },
    ],
  },
  {
    id: "software-development",
    index: "04",
    slug: "software-development",
    title: "Software & Product Engineering",
    menuDescription: "Build what you can't buy",
    answer:
      "Custom software engineering for processes that off-the-shelf tools don't fit — internal systems, customer portals, web and mobile applications, and integrations between systems that were never designed to talk to each other.",
    sections: [
      {
        heading: "When buying stops being cheaper than building",
        body: [
          "Buying should be the default. A product with thousands of customers has absorbed years of edge cases you would otherwise discover one at a time, and it costs a fraction of building the equivalent. Most businesses should exhaust that option before commissioning anything.",
          "The default stops holding in a specific situation: when the process being supported is the thing that makes the business different, and every available product forces it into a shape that removes the difference. At that point the licence fee is not the real cost — the real cost is the workaround, the spreadsheet beside the system, and the four people whose job is reconciling the two.",
          "The other honest trigger is integration weight. When most of the effort is moving data between tools that were never designed to talk, the tools are no longer the system; the glue is. Glue built by hand, in inboxes and exports, is expensive and invisible on any budget line.",
        ],
      },
      {
        heading: "What a discovery is actually for",
        body: [
          "Discovery has a bad name because it is often a formality — a few workshops, a document nobody reads, and a build that proceeds as originally imagined. Done properly it exists to answer one question: is the thing you are about to spend money on the thing that will actually help.",
          "That means mapping the process as it is really performed rather than as it is documented, finding where the exceptions live, and establishing which parts genuinely need to be built versus configured or dropped. It routinely reduces scope, and a discovery that only ever grows scope is a sales process.",
          "The output should be something you keep and can act on regardless of who builds it — a written understanding of the process, the integration surface, the data model and the risks, specific enough that a different supplier could quote from it.",
        ],
      },
      {
        heading: "The decisions that set total cost",
        body: [
          "The build is rarely the expensive part over a system's life. These are the choices that decide what it costs to own, and they are all easier to get right at the start than to change later.",
        ],
        points: [
          "Where the data lives and who owns the accounts — arranged at the end, this is negotiated at the worst possible moment.",
          "How the system authenticates people, and whether that survives the business growing or being acquired.",
          "Which integrations are load-bearing, and what the system does when one of them is down rather than merely slow.",
          "Whether routine changes need a developer, which determines whether the system ages into an asset or a bottleneck.",
          "What the handover looks like — documentation, environments and access — so the second supplier is not repeating the first one's discovery.",
        ],
      },
    ],
    seo: {
      title: "Software & Product Engineering",
      description:
        "Custom software, web and mobile applications, APIs and systems integration — engineered to be maintainable by your own team.",
      primaryTopic: "software and product engineering",
      secondaryTopics: ["web applications", "systems integration", "APIs"],
      intent: "commercial",
    },
    audience: ["A7", "A2", "A8"],
    phase: "P1",
    cta: {
      label: "Technical discovery call",
      href: "/contact/",
      tier: "T4",
      note: "Engineer to engineer, not a sales qualifier.",
    },
    services: [
      "custom-software",
      "web-applications",
      "systems-integration",
    ],
    process: [
      {
        index: 1,
        title: "Understand the process first",
        description:
          "The real one, including the steps that happen off-system. Building against the documented process is the most common reason software is delivered and then worked around.",
      },
      {
        index: 2,
        title: "Specify behaviour, not screens",
        description:
          "What must happen, under which conditions, with what result — including the unhappy paths. Most cost overrun lives in cases the requirements never mentioned.",
      },
      {
        index: 3,
        title: "Build in increments people can use",
        description:
          "One complete workflow at a time, released to real users. Requirements written before anyone has used a working version are the least reliable input available.",
      },
      {
        index: 4,
        title: "Hand over something maintainable",
        description:
          "Documented, tested, and built on choices your own team can hire for. Software nobody but us can change is a liability we have sold you.",
      },
    ],
    faqs: [
      {
        question: "Should we build or buy?",
        answer:
          "Buy wherever the process is genuinely standard, because a product carries maintenance you do not pay for. Build where the process is a real differentiator, or where every available product would need enough configuration to cost more than software would.",
      },
      {
        question: "How do we avoid being locked in to a supplier?",
        answer:
          "Own the repository and the infrastructure accounts from the first day, insist on mainstream technology choices, and require documentation as a deliverable rather than a favour. Lock-in is usually a contracting failure rather than a technical one.",
      },
    ],
  },
  {
    id: "ai-automation",
    index: "05",
    slug: "ai-automation",
    title: "AI & Automation",
    menuDescription: "Remove manual work",
    answer:
      "AI and automation applied to specific business processes — support, sales follow-up, back-office data work — with a clear boundary around what the system handles and what stays with a person.",
    sections: [
      {
        heading: "Automation is a scoping problem before it is a technology problem",
        body: [
          "The technology to automate most routine business processes has been available and affordable for years. The reason so much manual work survives is not that the tools are missing — it is that nobody has written down what the process actually is, including the exceptions, in enough detail to hand to a machine.",
          "Most processes that look simple turn out to have a long tail. The invoice flow is straightforward except for the three customers on bespoke terms, the currency case, and the thing someone does manually every month that was never documented because it takes them four minutes. Automating the clean path and ignoring the tail produces a system that handles eighty per cent of volume and creates a new manual process for the rest.",
          "So the first work is observation rather than implementation: what actually happens, how often each exception occurs, and what it currently costs in time. That analysis frequently changes what gets automated, and occasionally shows the process should be removed rather than automated.",
        ],
      },
      {
        heading: "Where AI genuinely helps — and where it does not",
        body: [
          "Rules-based automation and AI solve different problems, and the current enthusiasm blurs them in a way that leads to expensive mistakes. Deterministic work — if this field is set, route there; when this arrives, create that — should be deterministic. Putting a language model in that path adds cost, latency and a failure mode that did not previously exist.",
          "AI earns its place where the input is unstructured and the judgement is genuinely fuzzy: reading a document that arrives in fifty formats, summarising a long thread, classifying an enquiry by intent, drafting a first reply for a person to approve. These are tasks where a rule would need a thousand branches and still miss.",
          "The distinction matters commercially because the two have different risk profiles. A rule that breaks fails loudly and identically every time. A model that drifts fails quietly and differently each time, which is why anything consequential needs a person positioned to catch it.",
        ],
      },
      {
        heading: "Keeping a person in the loop, deliberately",
        body: [
          "The useful question is not whether a human reviews the output, but where in the flow they sit and what they are actually able to catch there. A reviewer shown a hundred confident summaries a day will approve the hundredth without reading it, and that is a design failure rather than a discipline failure.",
          "Better arrangements narrow what a person is asked to judge: surfacing only the cases the system is unsure about, showing the source alongside the output so verification is possible in seconds, and making the cost of rejection low. Where a decision carries real consequence — money moving, a commitment made to a customer — the system should propose and a person should dispose.",
          "We also write down what the system will not do. A boundary stated at the start is a design constraint everyone builds against; a boundary discovered later is an incident.",
        ],
      },
    ],
    seo: {
      title: "AI & Automation",
      description:
        "AI agents, chatbots, workflow automation and process digitisation — scoped around the work you actually want removed.",
      primaryTopic: "AI and business automation",
      secondaryTopics: ["AI agents", "workflow automation", "AI chatbots"],
      intent: "commercial",
    },
    audience: ["A6", "A7", "A2", "A5"],
    phase: "P1",
    cta: {
      label: "Request an automation assessment",
      href: "/contact/",
      tier: "T3",
      note: "We map the process and the risk before anything is built.",
    },
    services: [
      "ai-agents",
      "ai-chatbots",
      "workflow-automation",
      "sales-automation",
      "ai-consulting",
    ],
    process: [
      {
        index: 1,
        title: "Find the task, not the technology",
        description:
          "Start from work being done repeatedly, with its volume and error cost observed rather than estimated. A project that starts from a platform choice has skipped the part that decides whether it is worth doing.",
      },
      {
        index: 2,
        title: "Test feasibility honestly",
        description:
          "Whether the data and documentation a system would need actually exist and are accurate. This is where a fair number of proposals should stop, and saying so is the value.",
      },
      {
        index: 3,
        title: "Simplify before building",
        description:
          "Remove the steps that no longer have a reason to exist. This regularly returns more than the automation will, and it always reduces what has to be built and maintained.",
      },
      {
        index: 4,
        title: "Build one process end to end",
        description:
          "In production, with the exception path and failure behaviour designed in — not three in parallel, which discovers the same wrong assumption three times at triple the cost.",
      },
      {
        index: 5,
        title: "Hand over with an owner",
        description:
          "Documentation, alerting that reaches a person, and a named owner. Automations without one drift as systems change and credentials rotate, then quietly stop working.",
      },
    ],
    faqs: [
      {
        question: "Where should a first AI or automation project start?",
        answer:
          "With a high-frequency, low-judgement task where the cost of an error is recoverable. That combination is where these systems are reliable and where the recovered time is large enough to be worth measuring.",
      },
      {
        question: "What should not be automated?",
        answer:
          "Work whose value is the judgement in it, anything irreversible without a human check, and processes about to change anyway. Automating an unstable process fixes it in place at exactly the wrong moment.",
      },
    ],
  },
  {
    id: "data-analytics",
    index: "06",
    slug: "data-analytics",
    title: "Data & Business Intelligence",
    menuDescription: "Decisions from your own data",
    answer:
      "Bringing business data into one place and making it usable — reliable tracking, connected systems, and reporting that answers the questions leadership actually asks.",
    sections: [
      {
        heading: "Most reporting problems are collection problems",
        body: [
          "When leadership does not trust the dashboard, the instinct is to rebuild the dashboard. It rarely helps, because the dashboard is usually an accurate rendering of data that was collected badly.",
          "The common causes are mundane and cumulative: tracking installed once and never checked against a site that has since been rebuilt, events firing twice on some templates, a form that reports a submission before validation, campaign tagging applied inconsistently by three different people over two years. None of these is dramatic. Together they produce numbers that are close enough to look plausible and wrong enough to mislead.",
          "So the work starts at collection. Until a number can be traced from the interaction that produced it through to where it is displayed, presenting it more attractively only increases the confidence placed in it.",
        ],
      },
      {
        heading: "One number, three definitions",
        body: [
          "The second failure is definitional rather than technical. Marketing counts a lead when a form is submitted. Sales counts it when someone qualifies it. Finance counts it when it is invoiced. All three are defensible, all three are called 'leads', and the resulting meeting is an argument about arithmetic that is really an argument about vocabulary.",
          "Resolving this is not glamorous work — it is agreeing definitions and writing them down where the number is displayed, so a figure carries its own meaning rather than depending on who is in the room. It usually takes a fortnight and settles disputes that have been recurring for years.",
        ],
      },
      {
        heading: "Reporting that answers the question actually being asked",
        body: [
          "A dashboard that shows everything is a dashboard nobody reads. The useful ones start from the decisions the business genuinely makes on a rhythm — what to spend next month, which segment to pursue, whether the thing we changed worked — and show only what those decisions turn on.",
          "That means fewer numbers, each with a stated definition, a comparison period, and somewhere to click when the number looks wrong. It also means being honest about what the data cannot support: a figure derived from a broken chain should be labelled as such rather than presented alongside sound ones at equal weight.",
        ],
      },
    ],
    seo: {
      title: "Data & Business Intelligence",
      description:
        "Business intelligence, dashboards, analytics implementation and data integration for businesses running on disconnected tools.",
      primaryTopic: "business intelligence and data",
      secondaryTopics: ["dashboards", "analytics implementation"],
      intent: "commercial",
    },
    audience: ["A2", "A7", "A3"],
    phase: "P2",
    cta: {
      label: "Request an assessment",
      href: "/contact/",
      tier: "T3",
    },
    services: [
      "business-intelligence",
      "analytics-implementation",
    ],
    process: [
      {
        index: 1,
        title: "Agree what each number means",
        description:
          "Definitions before dashboards. Most disputes about figures turn out to be two teams applying different, individually reasonable rules to the same question.",
      },
      {
        index: 2,
        title: "Assess the sources",
        description:
          "Which systems hold the data, how reliable each one is, and which gaps have to close before anything built on them can be trusted.",
      },
      {
        index: 3,
        title: "Automate the assembly",
        description:
          "Pipelines with a refresh schedule and failure alerting, so reporting stops being a monthly manual exercise that is already out of date when it lands.",
      },
      {
        index: 4,
        title: "Build for decisions",
        description:
          "Each dashboard supports a specific recurring decision and has an owner. Reporting with no decision attached goes unopened and dilutes attention from the reporting that matters.",
      },
    ],
    faqs: [
      {
        question: "Why do our reports disagree with each other?",
        answer:
          "Almost always because the underlying definitions differ — a different date field, a different exclusion, a different treatment of cancellations. It is a business agreement problem, and no tool resolves it.",
      },
      {
        question: "Do we need a data warehouse?",
        answer:
          "Only when reporting genuinely needs data from several systems at once. A single well-instrumented source answers more questions than most organisations expect, at a fraction of the cost of a platform build.",
      },
    ],
  },
];

export function getPractice(slug: string): Practice | undefined {
  return practices.find((p) => p.slug === slug);
}
