/**
 * The six capability practices.
 *
 * Replaces the six services on the live site. AI Powered Solutions and
 * Business Automation are merged (both claimed "Workflow Automation");
 * Data & BI is promoted from a bullet to a practice.
 * See docs/architecture/01-strategy-and-positioning.md.
 */

import type { Practice } from "@/types/content";

export const practices: Practice[] = [
  {
    id: "search-ai-visibility",
    index: "01",
    slug: "search-ai-visibility",
    title: "Search & AI Visibility",
    menuDescription: "Get found on Google and in AI answers",
    answer:
      "Search and AI visibility is the work of making a business findable wherever buyers now look — traditional search results, AI Overviews, and the answers generated by ChatGPT, Perplexity and Gemini. It combines technical SEO, content structure and entity clarity into one programme.",
    seo: {
      title: "Search & AI Visibility",
      description:
        "Get found on Google and in AI answers. Technical SEO, AEO, GEO and entity optimisation, delivered as one programme.",
      primaryTopic: "search and AI visibility",
      secondaryTopics: ["SEO", "AEO", "GEO", "AI search optimisation"],
      intent: "commercial",
    },
    audience: ["A3", "A4", "A1", "A2"],
    phase: "P1",
    cta: {
      label: "Request an AI visibility assessment",
      href: "/contact/",
      tier: "T3",
      note: "We measure where you appear today, and where you don't.",
    },
    services: [
      "seo",
      "ai-search-optimisation",
      "technical-seo",
      "answer-engine-optimisation",
      "generative-engine-optimisation",
      "ai-optimisation",
      "search-experience-optimisation",
      "google-business-profile",
    ],
    process: [
      {
        index: 1,
        title: "Measure what exists",
        description:
          "Crawl, index and entity audit, plus a fixed prompt set run against the major AI systems to establish a real baseline.",
        duration: "Weeks 1–2",
      },
      {
        index: 2,
        title: "Fix the structure",
        description:
          "Technical debt, information architecture, schema and crawlability — the constraints that cap everything else.",
        duration: "Weeks 3–6",
      },
      {
        index: 3,
        title: "Build the answers",
        description:
          "Content shaped for extraction and citation, mapped to the queries your buyers actually use.",
        duration: "Weeks 6–12",
      },
      {
        index: 4,
        title: "Measure and iterate",
        description:
          "Rankings, citations and enquiries tracked together. The same prompt set re-run monthly.",
        duration: "Ongoing",
      },
    ],
    faqs: [
      {
        question: "How is AI search optimisation different from SEO?",
        answer:
          "SEO optimises for a ranked list of links. AI search optimisation targets being used as the source inside a generated answer, which rewards clear structure, extractable definitions, and an unambiguous entity. The foundations overlap; the content shape does not.",
      },
      {
        question: "How long before we see results?",
        answer:
          "Technical fixes can show within weeks. Meaningful ranking and citation movement typically starts around week 10 to 12. Anyone promising faster is describing a different, shorter-lived tactic.",
      },
    ],
  },
  {
    id: "digital-marketing",
    index: "02",
    slug: "digital-marketing",
    title: "Digital Marketing & Growth",
    menuDescription: "Build and convert demand",
    answer:
      "Digital marketing and growth covers the demand side of the business: strategy, paid and organic acquisition, content, and the conversion work that turns traffic into enquiries you can actually trace back to revenue.",
    seo: {
      title: "Digital Marketing & Growth",
      description:
        "Performance marketing, content, conversion optimisation and growth strategy — measured against enquiries, not impressions.",
      primaryTopic: "digital marketing and growth",
      secondaryTopics: ["performance marketing", "conversion optimisation"],
      intent: "commercial",
    },
    audience: ["A3", "A5", "A1"],
    phase: "P1",
    cta: {
      label: "Talk to a strategist",
      href: "/contact/",
      tier: "T4",
      note: "30 minutes. We'll tell you where the gaps are.",
    },
    services: [
      "digital-strategy",
      "performance-marketing",
      "conversion-rate-optimization",
    ],
  },
  {
    id: "web-development",
    index: "03",
    slug: "web-development",
    title: "Websites & Digital Experience",
    menuDescription: "Sites that are found and convert",
    answer:
      "Website design and development for businesses that need a site to do commercial work — be discoverable, load fast, explain something complicated clearly, and turn visitors into enquiries.",
    seo: {
      title: "Websites & Digital Experience",
      description:
        "Corporate websites, e-commerce, web applications and redesigns built for discoverability, speed and conversion.",
      primaryTopic: "website design and development",
      secondaryTopics: ["web design", "corporate websites", "e-commerce"],
      intent: "commercial",
    },
    audience: ["A1", "A3", "A7"],
    phase: "P1",
    cta: {
      label: "Discuss your project",
      href: "/contact/",
      tier: "T4",
    },
    services: [
      "corporate-websites",
      "ui-ux-design",
      "website-redesign",
      "website-performance",
    ],
  },
  {
    id: "software-development",
    index: "04",
    slug: "software-development",
    title: "Software & Product Engineering",
    menuDescription: "Build what you can't buy",
    answer:
      "Custom software engineering for processes that off-the-shelf tools don't fit — internal systems, customer portals, web and mobile applications, and integrations between systems that were never designed to talk to each other.",
    seo: {
      title: "Software & Product Engineering",
      description:
        "Custom software, web and mobile applications, APIs and systems integration — engineered to be maintainable by your own team.",
      primaryTopic: "custom software development",
      secondaryTopics: ["web applications", "systems integration", "APIs"],
      intent: "commercial",
    },
    audience: ["A7", "A2", "A8"],
    phase: "P1",
    cta: {
      label: "Technical discovery call",
      href: "/contact/",
      tier: "T4",
      note: "Engineer to engineer, not a sales qualifier.",
    },
    services: [
      "custom-software",
      "web-applications",
      "systems-integration",
    ],
  },
  {
    id: "ai-automation",
    index: "05",
    slug: "ai-automation",
    title: "AI & Automation",
    menuDescription: "Remove manual work",
    answer:
      "AI and automation applied to specific business processes — support, sales follow-up, back-office data work — with a clear boundary around what the system handles and what stays with a person.",
    seo: {
      title: "AI & Automation",
      description:
        "AI agents, chatbots, workflow automation and process digitisation — scoped around the work you actually want removed.",
      primaryTopic: "AI and business automation",
      secondaryTopics: ["AI agents", "workflow automation", "AI chatbots"],
      intent: "commercial",
    },
    audience: ["A6", "A7", "A2", "A5"],
    phase: "P1",
    cta: {
      label: "Request an automation assessment",
      href: "/contact/",
      tier: "T3",
      note: "We map the process and the risk before anything is built.",
    },
    services: [
      "ai-agents",
      "ai-chatbots",
      "workflow-automation",
      "sales-automation",
      "ai-consulting",
    ],
  },
  {
    id: "data-analytics",
    index: "06",
    slug: "data-analytics",
    title: "Data & Business Intelligence",
    menuDescription: "Decisions from your own data",
    answer:
      "Bringing business data into one place and making it usable — reliable tracking, connected systems, and reporting that answers the questions leadership actually asks.",
    seo: {
      title: "Data & Business Intelligence",
      description:
        "Business intelligence, dashboards, analytics implementation and data integration for businesses running on disconnected tools.",
      primaryTopic: "business intelligence and data",
      secondaryTopics: ["dashboards", "analytics implementation"],
      intent: "commercial",
    },
    audience: ["A2", "A7", "A3"],
    phase: "P2",
    cta: {
      label: "Request an assessment",
      href: "/contact/",
      tier: "T3",
    },
    services: [
      "business-intelligence",
      "analytics-implementation",
    ],
  },
];

export function getPractice(slug: string): Practice | undefined {
  return practices.find((p) => p.slug === slug);
}
