/**
 * BizzFly Centralized Image Registry
 *
 * AUTO-GENERATED & STRICTLY ENFORCED.
 * Every image asset has a unique ID, non-keyword-stuffed descriptive alt text,
 * explicit intrinsic dimensions, and semantic metadata.
 */

import type { ImageMetadata } from "./types";

export const imageRegistry: Record<string, ImageMetadata> = {
  "home-hero-growth-team": {
    id: "home-hero-growth-team",
    src: "/images/home/hero-growth-ai-team.webp",
    alt: "Digital growth and engineering team collaborating around shared monitors in a modern technology office",
    topic: "Digital Growth & AI",
    category: "digital-growth",
    type: "human",
    aspectRatio: "16:9",
    width: 1200,
    height: 675,
    usage: "hero",
    caption: "BizzFly digital growth, AI, and systems engineering specialists in Pune.",
  },
  "home-what-we-do-strategists": {
    id: "home-what-we-do-strategists",
    src: "/images/home/what-we-do-strategists.webp",
    alt: "Digital strategists analyzing business growth roadmap and multi-channel discoverability opportunities",
    topic: "What BizzFly Does",
    category: "digital-growth",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "section",
    caption: "Strategic alignment connecting discoverability directly to operational systems.",
  },
  "home-search-visibility-analyst": {
    id: "home-search-visibility-analyst",
    src: "/images/home/search-visibility-analyst.webp",
    alt: "Search visibility specialist evaluating organic search query trends and performance analytics",
    topic: "Search Visibility",
    category: "services",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "section",
    caption: "Analyzing multi-surface search retrieval across Google and AI engines.",
  },
  "home-ai-search-workflow": {
    id: "home-ai-search-workflow",
    src: "/images/home/ai-search-workflow.webp",
    alt: "Consultants researching AI search answer engine citations and generative retrieval patterns",
    topic: "AI Search & AEO",
    category: "technology",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "section",
    caption: "Structuring business data for citation in generative AI responses.",
  },
  "home-automation-operations": {
    id: "home-automation-operations",
    src: "/images/home/automation-operations-workflow.webp",
    alt: "Operations professionals reviewing automated business workflow diagrams and connected services",
    topic: "Business Automation",
    category: "automation",
    type: "business",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "section",
    caption: "Connecting lead capture, CRM pipelines, and backend operational workflows.",
  },
  "home-technology-engineers": {
    id: "home-technology-engineers",
    src: "/images/home/technology-engineering-team.webp",
    alt: "Software engineers and technical architects collaborating on application code and infrastructure standards",
    topic: "Technology & Engineering",
    category: "technology",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "section",
    caption: "Engineers building reliable, accessible web applications and custom software.",
  },
  "practice-search-ai-visibility": {
    id: "practice-search-ai-visibility",
    src: "/images/services/practice-search-ai-visibility.webp",
    alt: "Search visibility team reviewing multi-platform presence across Google, AI Overviews, and maps",
    topic: "Search & AI Visibility Practice",
    category: "services",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "hero",
  },
  "practice-digital-marketing": {
    id: "practice-digital-marketing",
    src: "/images/services/practice-digital-marketing.webp",
    alt: "Digital marketing specialists reviewing organic and paid acquisition performance data",
    topic: "Digital Marketing Practice",
    category: "services",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "hero",
  },
  "practice-web-development": {
    id: "practice-web-development",
    src: "/images/services/practice-web-development.webp",
    alt: "Web development engineers working with modern Next.js and TypeScript codebases on laptop screens",
    topic: "Web Development Practice",
    category: "services",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "hero",
  },
  "practice-software-development": {
    id: "practice-software-development",
    src: "/images/services/practice-software-development.webp",
    alt: "Software engineering workspace displaying source code architecture and integration testing",
    topic: "Software Development Practice",
    category: "services",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "hero",
  },
  "practice-ai-automation": {
    id: "practice-ai-automation",
    src: "/images/services/practice-ai-automation.webp",
    alt: "Automation and artificial intelligence engineers deploying intelligent business agents",
    topic: "AI & Automation Practice",
    category: "services",
    type: "business",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "hero",
  },
  "practice-data-analytics": {
    id: "practice-data-analytics",
    src: "/images/services/practice-data-analytics.webp",
    alt: "Data visualization dashboard showing commercial metrics, conversion rates, and revenue performance",
    topic: "Data & Analytics Practice",
    category: "services",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "hero",
  },
  "service-seo": {
    id: "service-seo",
    src: "/images/services/service-seo-strategy.webp",
    alt: "SEO professional explaining technical crawl optimization and keyword intent to team members",
    topic: "Search Engine Optimisation",
    category: "services",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-ai-search-optimisation": {
    id: "service-ai-search-optimisation",
    src: "/images/services/service-ai-search-optimisation.webp",
    alt: "Modern computer interface analyzing knowledge graph entities and AI citation paths",
    topic: "AI Search Optimisation",
    category: "services",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-technical-seo": {
    id: "service-technical-seo",
    src: "/images/services/service-technical-seo.webp",
    alt: "Technical SEO developer examining HTML source code and structured data validation",
    topic: "Technical SEO",
    category: "services",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-ai-agents": {
    id: "service-ai-agents",
    src: "/images/services/service-ai-agents.webp",
    alt: "Software engineer configuring autonomous AI agents for document and operational handling",
    topic: "AI Agents",
    category: "services",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-workflow-automation": {
    id: "service-workflow-automation",
    src: "/images/services/service-workflow-automation.webp",
    alt: "Operations consultant mapping multi-stage business workflow steps on a desk surface",
    topic: "Workflow Automation",
    category: "services",
    type: "process",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-corporate-websites": {
    id: "service-corporate-websites",
    src: "/images/services/service-corporate-websites.webp",
    alt: "Corporate executive reviewing new corporate website layout on tablet in modern boardroom",
    topic: "Corporate Websites",
    category: "services",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-answer-engine-optimisation": {
    id: "service-answer-engine-optimisation",
    src: "/images/services/service-answer-engine-optimisation.webp",
    alt: "Content strategist writing direct answer definitions optimized for search engine featured snippets",
    topic: "Answer Engine Optimisation",
    category: "services",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-generative-engine-optimisation": {
    id: "service-generative-engine-optimisation",
    src: "/images/services/service-generative-engine-optimisation.webp",
    alt: "Technical team analyzing generative AI query results and brand source citations",
    topic: "Generative Engine Optimisation",
    category: "services",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-ai-optimisation": {
    id: "service-ai-optimisation",
    src: "/images/services/service-ai-optimisation.webp",
    alt: "Machine learning practitioner testing prompt evaluations and output quality parameters",
    topic: "AI Optimisation",
    category: "services",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-search-experience-optimisation": {
    id: "service-search-experience-optimisation",
    src: "/images/services/service-search-experience-optimisation.webp",
    alt: "UX designer analyzing digital user interactions and scroll heatmaps across web pages",
    topic: "Search Experience Optimisation",
    category: "services",
    type: "process",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-google-business-profile": {
    id: "service-google-business-profile",
    src: "/images/services/service-google-business-profile.webp",
    alt: "Local business owner managing storefront discovery, Google Maps listings, and customer reviews",
    topic: "Google Business Profile",
    category: "services",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-custom-software": {
    id: "service-custom-software",
    src: "/images/services/service-custom-software.webp",
    alt: "Software engineer designing custom enterprise application architecture on dual monitors",
    topic: "Custom Software",
    category: "services",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-web-applications": {
    id: "service-web-applications",
    src: "/images/services/service-web-applications.webp",
    alt: "Full-stack developer building robust web application APIs and responsive user interfaces",
    topic: "Web Applications",
    category: "services",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-ui-ux-design": {
    id: "service-ui-ux-design",
    src: "/images/services/service-ui-ux-design.webp",
    alt: "Digital product designer sketching wireframes and user interface flows in notebook",
    topic: "UI/UX Design",
    category: "services",
    type: "process",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-systems-integration": {
    id: "service-systems-integration",
    src: "/images/services/service-systems-integration.webp",
    alt: "Server infrastructure and networked cloud systems facilitating enterprise data exchange",
    topic: "Systems Integration",
    category: "services",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-ai-chatbots": {
    id: "service-ai-chatbots",
    src: "/images/services/service-ai-chatbots.webp",
    alt: "Customer support specialist collaborating with AI chatbot assistant to resolve client inquiries",
    topic: "AI Chatbots",
    category: "services",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-sales-automation": {
    id: "service-sales-automation",
    src: "/images/services/service-sales-automation.webp",
    alt: "Sales development team reviewing automated lead qualification metrics and follow-up cadences",
    topic: "Sales Automation",
    category: "services",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-ai-consulting": {
    id: "service-ai-consulting",
    src: "/images/services/service-ai-consulting.webp",
    alt: "AI strategy consultant presenting technical adoption roadmap to executive stakeholders",
    topic: "AI Consulting",
    category: "services",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-digital-strategy": {
    id: "service-digital-strategy",
    src: "/images/services/service-digital-strategy.webp",
    alt: "Business leadership team evaluating digital transformation priorities in conference room",
    topic: "Digital Strategy",
    category: "services",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-performance-marketing": {
    id: "service-performance-marketing",
    src: "/images/services/service-performance-marketing.webp",
    alt: "Growth marketing team measuring paid and organic acquisition metrics across digital channels",
    topic: "Performance Marketing",
    category: "services",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-conversion-rate-optimization": {
    id: "service-conversion-rate-optimization",
    src: "/images/services/service-conversion-rate-optimization.webp",
    alt: "UX and conversion analyst inspecting user journey drop-off data on modern laptop",
    topic: "Conversion Rate Optimization",
    category: "services",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-business-intelligence": {
    id: "service-business-intelligence",
    src: "/images/services/service-business-intelligence.webp",
    alt: "Executive reviewing consolidated business intelligence charts and growth forecasting figures",
    topic: "Business Intelligence",
    category: "services",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-analytics-implementation": {
    id: "service-analytics-implementation",
    src: "/images/services/service-analytics-implementation.webp",
    alt: "Measurement engineer validating custom event telemetry and server-side tracking pipelines",
    topic: "Analytics Implementation",
    category: "services",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-website-performance": {
    id: "service-website-performance",
    src: "/images/services/service-website-performance.webp",
    alt: "Web engineer optimizing browser rendering speed, server caching, and network waterfall",
    topic: "Website Performance",
    category: "services",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-website-redesign": {
    id: "service-website-redesign",
    src: "/images/services/service-website-redesign.webp",
    alt: "Design team collaborating on modern typography, color systems, and page layouts for web redesign",
    topic: "Website Redesign",
    category: "services",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-seo-audit": {
    id: "service-seo-audit",
    src: "/images/services/service-seo-audit.webp",
    alt: "SEO director auditing website architecture, indexation barriers, and organic competitive rank",
    topic: "SEO Audit",
    category: "services",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-on-page-seo": {
    id: "service-on-page-seo",
    src: "/images/services/service-on-page-seo.webp",
    alt: "Content specialist writing semantic content with clear heading hierarchy and descriptive internal links",
    topic: "On-Page SEO",
    category: "services",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-local-seo": {
    id: "service-local-seo",
    src: "/images/services/service-local-seo.webp",
    alt: "Urban area map highlighting geographic local search visibility markers for regional businesses",
    topic: "Local SEO",
    category: "services",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-enterprise-seo": {
    id: "service-enterprise-seo",
    src: "/images/services/service-enterprise-seo.webp",
    alt: "Corporate enterprise headquarters representing large-scale multi-market digital discoverability",
    topic: "Enterprise SEO",
    category: "services",
    type: "business",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-ecommerce-seo": {
    id: "service-ecommerce-seo",
    src: "/images/services/service-ecommerce-seo.webp",
    alt: "Retail commerce team analyzing product category organic rankings and checkout conversion funnel",
    topic: "E-commerce SEO",
    category: "services",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-seo-migration": {
    id: "service-seo-migration",
    src: "/images/services/service-seo-migration.webp",
    alt: "Engineering team monitoring website traffic transition and DNS redirection during platform migration",
    topic: "SEO Migration",
    category: "services",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-content-strategy": {
    id: "service-content-strategy",
    src: "/images/services/service-content-strategy.webp",
    alt: "Strategist researching customer intent clusters and outlining authoritative informational guides",
    topic: "Content Strategy",
    category: "services",
    type: "process",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-digital-pr": {
    id: "service-digital-pr",
    src: "/images/services/service-digital-pr.webp",
    alt: "Communication professionals networking and building media relationships for earned brand authority",
    topic: "Digital PR",
    category: "services",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-structured-data": {
    id: "service-structured-data",
    src: "/images/services/service-structured-data.webp",
    alt: "Developer writing Schema JSON-LD markup to enrich search results with structured organization data",
    topic: "Structured Data",
    category: "services",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-site-architecture": {
    id: "service-site-architecture",
    src: "/images/services/service-site-architecture.webp",
    alt: "Information architect planning URL hierarchy and taxonomy relationships on whiteboard",
    topic: "Site Architecture",
    category: "services",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-ai-readiness-assessment": {
    id: "service-ai-readiness-assessment",
    src: "/images/services/service-ai-readiness-assessment.webp",
    alt: "Enterprise consultant conducting an evaluation of data governance and AI technical readiness",
    topic: "AI Readiness Assessment",
    category: "services",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-ai-document-processing": {
    id: "service-ai-document-processing",
    src: "/images/services/service-ai-document-processing.webp",
    alt: "Digital document capture and optical character recognition converting physical records into data",
    topic: "AI Document Processing",
    category: "services",
    type: "process",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-api-development": {
    id: "service-api-development",
    src: "/images/services/service-api-development.webp",
    alt: "Backend engineer programming robust REST and GraphQL endpoints in development environment",
    topic: "API Development",
    category: "services",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-crm-implementation": {
    id: "service-crm-implementation",
    src: "/images/services/service-crm-implementation.webp",
    alt: "CRM systems administrator configuring customer record stages and automated deal tracking",
    topic: "CRM Implementation",
    category: "services",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-marketing-automation": {
    id: "service-marketing-automation",
    src: "/images/services/service-marketing-automation.webp",
    alt: "Marketing operations specialist building email nurture workflows and automated lead scoring",
    topic: "Marketing Automation",
    category: "services",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-customer-portals": {
    id: "service-customer-portals",
    src: "/images/services/service-customer-portals.webp",
    alt: "Modern business office where clients access self-service account management and document portals",
    topic: "Customer Portals",
    category: "services",
    type: "business",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-reporting-dashboards": {
    id: "service-reporting-dashboards",
    src: "/images/services/service-reporting-dashboards.webp",
    alt: "Data specialist discussing real-time executive dashboard visualizations with colleagues",
    topic: "Reporting Dashboards",
    category: "services",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-cloud-migration": {
    id: "service-cloud-migration",
    src: "/images/services/service-cloud-migration.webp",
    alt: "Global digital cloud network representing secure data center migration and scalable architecture",
    topic: "Cloud Migration",
    category: "services",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-website-maintenance": {
    id: "service-website-maintenance",
    src: "/images/services/service-website-maintenance.webp",
    alt: "Support engineer verifying server health checks, security patches, and automated backup routines",
    topic: "Website Maintenance",
    category: "services",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "service-accessibility-audit": {
    id: "service-accessibility-audit",
    src: "/images/services/service-accessibility-audit.webp",
    alt: "Accessibility specialist testing screen reader navigation, keyboard focus rings, and WCAG contrast",
    topic: "Accessibility Audit",
    category: "services",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "industry-manufacturing": {
    id: "industry-manufacturing",
    src: "/images/industries/industry-manufacturing.webp",
    alt: "Industrial engineer inspecting automated manufacturing production machinery and equipment",
    topic: "Manufacturing",
    category: "industries",
    type: "business",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "industry-real-estate": {
    id: "industry-real-estate",
    src: "/images/industries/industry-real-estate.webp",
    alt: "Modern commercial real estate architecture showcasing property development projects",
    topic: "Real Estate",
    category: "industries",
    type: "business",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "industry-education": {
    id: "industry-education",
    src: "/images/industries/industry-education.webp",
    alt: "Students and faculty collaborating in contemporary higher education academic library",
    topic: "Education",
    category: "industries",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "industry-professional-services": {
    id: "industry-professional-services",
    src: "/images/industries/industry-professional-services.webp",
    alt: "Professional advisors discussing client advisory engagement in corporate meeting space",
    topic: "Professional Services",
    category: "industries",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "industry-saas": {
    id: "industry-saas",
    src: "/images/industries/industry-saas.webp",
    alt: "SaaS product team mapping user onboarding journey and subscription metrics",
    topic: "SaaS",
    category: "industries",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "industry-healthcare": {
    id: "industry-healthcare",
    src: "/images/industries/industry-healthcare.webp",
    alt: "Healthcare professionals reviewing clinical records on digital tablet in medical setting",
    topic: "Healthcare",
    category: "industries",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "industry-financial-services": {
    id: "industry-financial-services",
    src: "/images/industries/industry-financial-services.webp",
    alt: "Finance professional reviewing investment portfolios and banking analytics on dual screens",
    topic: "Financial Services",
    category: "industries",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "industry-ecommerce": {
    id: "industry-ecommerce",
    src: "/images/industries/industry-ecommerce.webp",
    alt: "Modern fulfillment warehouse and online retail distribution operations",
    topic: "E-commerce",
    category: "industries",
    type: "business",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "industry-logistics": {
    id: "industry-logistics",
    src: "/images/industries/industry-logistics.webp",
    alt: "Logistics supply chain manager coordinating freight shipments and warehouse storage",
    topic: "Logistics",
    category: "industries",
    type: "business",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "industry-it-services": {
    id: "industry-it-services",
    src: "/images/industries/industry-it-services.webp",
    alt: "IT services and systems support team collaborating in networked enterprise operations center",
    topic: "IT Services",
    category: "industries",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "industry-hospitality": {
    id: "industry-hospitality",
    src: "/images/industries/industry-hospitality.webp",
    alt: "Boutique luxury hotel lobby highlighting digital guest booking and hospitality services",
    topic: "Hospitality",
    category: "industries",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "industry-startups": {
    id: "industry-startups",
    src: "/images/industries/industry-startups.webp",
    alt: "Early-stage technology startup founders pitching growth roadmap in agile workspace",
    topic: "Startups",
    category: "industries",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "industry-technology": {
    id: "industry-technology",
    src: "/images/industries/industry-technology.webp",
    alt: "Semiconductor microchip and advanced electronics engineering hardware",
    topic: "Technology Sector",
    category: "industries",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "industry-automotive": {
    id: "industry-automotive",
    src: "/images/industries/industry-automotive.webp",
    alt: "Modern automotive engineering laboratory developing connected vehicle systems",
    topic: "Automotive",
    category: "industries",
    type: "business",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "industry-construction": {
    id: "industry-construction",
    src: "/images/industries/industry-construction.webp",
    alt: "Civil engineer inspecting commercial building construction blueprints and structural site work",
    topic: "Construction",
    category: "industries",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "industry-legal-services": {
    id: "industry-legal-services",
    src: "/images/industries/industry-legal-services.webp",
    alt: "Legal counsel library symbolizing corporate legal practice, compliance, and governance",
    topic: "Legal Services",
    category: "industries",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "industry-accounting": {
    id: "industry-accounting",
    src: "/images/industries/industry-accounting.webp",
    alt: "Chartered accountant auditing corporate financial statements and tax filings",
    topic: "Accounting",
    category: "industries",
    type: "process",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "industry-recruitment": {
    id: "industry-recruitment",
    src: "/images/industries/industry-recruitment.webp",
    alt: "Talent acquisition partner conducting interview consultation with career candidate",
    topic: "Recruitment",
    category: "industries",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "industry-energy": {
    id: "industry-energy",
    src: "/images/industries/industry-energy.webp",
    alt: "Renewable solar and wind energy infrastructure powering sustainable electrical grid",
    topic: "Energy",
    category: "industries",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "industry-travel": {
    id: "industry-travel",
    src: "/images/industries/industry-travel.webp",
    alt: "Travel technology platform user booking flight and itinerary routes on mobile device",
    topic: "Travel",
    category: "industries",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "industry-nonprofit": {
    id: "industry-nonprofit",
    src: "/images/industries/industry-nonprofit.webp",
    alt: "Community non-profit volunteers collaborating on social impact initiative",
    topic: "Nonprofit",
    category: "industries",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "industry-media": {
    id: "industry-media",
    src: "/images/industries/industry-media.webp",
    alt: "Digital publishing editorial workspace with newspapers and digital journalism content",
    topic: "Media",
    category: "industries",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "industry-agriculture": {
    id: "industry-agriculture",
    src: "/images/industries/industry-agriculture.webp",
    alt: "Agricultural technologist monitoring automated crop irrigation and yield analytics",
    topic: "Agriculture",
    category: "industries",
    type: "business",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "industry-b2b-services": {
    id: "industry-b2b-services",
    src: "/images/industries/industry-b2b-services.webp",
    alt: "B2B enterprise service partners meeting to discuss contract deliverables and scope",
    topic: "B2B Services",
    category: "industries",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "industry-d2c-brands": {
    id: "industry-d2c-brands",
    src: "/images/industries/industry-d2c-brands.webp",
    alt: "Contemporary retail boutique showcasing direct-to-consumer lifestyle merchandise",
    topic: "D2C Brands",
    category: "industries",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "industry-smes": {
    id: "industry-smes",
    src: "/images/industries/industry-smes.webp",
    alt: "Small and medium business owners discussing operations and cash flow in studio office",
    topic: "SMEs",
    category: "industries",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-generate-more-leads": {
    id: "use-case-generate-more-leads",
    src: "/images/use-cases/use-case-generate-more-leads.webp",
    alt: "Marketing director evaluating commercial lead pipeline growth charts and attribution reports",
    topic: "Generate More Leads",
    category: "use-cases",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-get-found-in-ai-search": {
    id: "use-case-get-found-in-ai-search",
    src: "/images/use-cases/use-case-get-found-in-ai-search.webp",
    alt: "Professional searching across AI conversational interfaces and structured knowledge cards",
    topic: "Get Found in AI Search",
    category: "use-cases",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-reduce-manual-work": {
    id: "use-case-reduce-manual-work",
    src: "/images/use-cases/use-case-reduce-manual-work.webp",
    alt: "Organized modern workplace representing automated administrative efficiency and paperless workflows",
    topic: "Reduce Manual Work",
    category: "use-cases",
    type: "business",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-increase-organic-traffic": {
    id: "use-case-increase-organic-traffic",
    src: "/images/use-cases/use-case-increase-organic-traffic.webp",
    alt: "Analytics display illustrating strong upward trajectory in organic web visitors over quarters",
    topic: "Increase Organic Traffic",
    category: "use-cases",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-automate-sales-follow-up": {
    id: "use-case-automate-sales-follow-up",
    src: "/images/use-cases/use-case-automate-sales-follow-up.webp",
    alt: "Account executive conducting scheduled client consultation with CRM record on laptop",
    topic: "Automate Sales Follow-Up",
    category: "use-cases",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-automate-customer-support": {
    id: "use-case-automate-customer-support",
    src: "/images/use-cases/use-case-automate-customer-support.webp",
    alt: "Customer support specialist assisting user queries supported by automated response knowledge base",
    topic: "Automate Customer Support",
    category: "use-cases",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-improve-website-conversion": {
    id: "use-case-improve-website-conversion",
    src: "/images/use-cases/use-case-improve-website-conversion.webp",
    alt: "Product team testing landing page variants to eliminate conversion friction points",
    topic: "Improve Website Conversion",
    category: "use-cases",
    type: "process",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-rank-in-local-search": {
    id: "use-case-rank-in-local-search",
    src: "/images/use-cases/use-case-rank-in-local-search.webp",
    alt: "Smartphone displaying localized search results and map navigation to verified regional business",
    topic: "Rank in Local Search",
    category: "use-cases",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-improve-operational-efficiency": {
    id: "use-case-improve-operational-efficiency",
    src: "/images/use-cases/use-case-improve-operational-efficiency.webp",
    alt: "Operations directors identifying bottlenecks and streamlining internal project handoffs",
    topic: "Improve Operational Efficiency",
    category: "use-cases",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-connect-business-systems": {
    id: "use-case-connect-business-systems",
    src: "/images/use-cases/use-case-connect-business-systems.webp",
    alt: "Seamless digital integration connecting databases, billing gateways, and customer portals",
    topic: "Connect Business Systems",
    category: "use-cases",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-modernise-legacy-processes": {
    id: "use-case-modernise-legacy-processes",
    src: "/images/use-cases/use-case-modernise-legacy-processes.webp",
    alt: "Enterprise team replacing manual spreadsheet tracking with real-time digital software",
    topic: "Modernise Legacy Processes",
    category: "use-cases",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-introduce-ai-into-operations": {
    id: "use-case-introduce-ai-into-operations",
    src: "/images/use-cases/use-case-introduce-ai-into-operations.webp",
    alt: "Business team integrating machine learning automation into daily back-office workflows",
    topic: "Introduce AI into Operations",
    category: "use-cases",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-build-a-custom-business-platform": {
    id: "use-case-build-a-custom-business-platform",
    src: "/images/use-cases/use-case-build-a-custom-business-platform.webp",
    alt: "Operations manager interacting with bespoke company platform dashboard on modern tablet",
    topic: "Build a Custom Business Platform",
    category: "use-cases",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-improve-digital-presence": {
    id: "use-case-improve-digital-presence",
    src: "/images/use-cases/use-case-improve-digital-presence.webp",
    alt: "Unified brand experience displayed across multiple mobile, tablet, and desktop monitors",
    topic: "Improve Digital Presence",
    category: "use-cases",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-build-scalable-digital-infrastructure": {
    id: "use-case-build-scalable-digital-infrastructure",
    src: "/images/use-cases/use-case-build-scalable-digital-infrastructure.webp",
    alt: "High-performance enterprise cloud data center providing fault-tolerant uptime",
    topic: "Build Scalable Digital Infrastructure",
    category: "use-cases",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-improve-customer-experience": {
    id: "use-case-improve-customer-experience",
    src: "/images/use-cases/use-case-improve-customer-experience.webp",
    alt: "Client enjoying smooth digital interaction and immediate service delivery",
    topic: "Improve Customer Experience",
    category: "use-cases",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-reduce-customer-churn": {
    id: "use-case-reduce-customer-churn",
    src: "/images/use-cases/use-case-reduce-customer-churn.webp",
    alt: "Account executive conducting quarterly check-in to secure customer satisfaction and renewal",
    topic: "Reduce Customer Churn",
    category: "use-cases",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-shorten-sales-cycle": {
    id: "use-case-shorten-sales-cycle",
    src: "/images/use-cases/use-case-shorten-sales-cycle.webp",
    alt: "Business partners concluding agreement terms following streamlined evaluation process",
    topic: "Shorten Sales Cycle",
    category: "use-cases",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-qualify-leads-automatically": {
    id: "use-case-qualify-leads-automatically",
    src: "/images/use-cases/use-case-qualify-leads-automatically.webp",
    alt: "Automated routing system sorting high-intent inbound inquiries directly to technical specialists",
    topic: "Qualify Leads Automatically",
    category: "use-cases",
    type: "process",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-speed-up-quoting": {
    id: "use-case-speed-up-quoting",
    src: "/images/use-cases/use-case-speed-up-quoting.webp",
    alt: "Sales engineer generating dynamic pricing and instant scope estimates using configured CPQ software",
    topic: "Speed Up Quoting",
    category: "use-cases",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-prove-marketing-roi": {
    id: "use-case-prove-marketing-roi",
    src: "/images/use-cases/use-case-prove-marketing-roi.webp",
    alt: "Finance and marketing leaders reviewing transparent customer acquisition cost and return calculations",
    topic: "Prove Marketing ROI",
    category: "use-cases",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-recover-lost-traffic": {
    id: "use-case-recover-lost-traffic",
    src: "/images/use-cases/use-case-recover-lost-traffic.webp",
    alt: "Senior web technologist diagnosing search penalty drops and restoring organic crawl pathways",
    topic: "Recover Lost Traffic",
    category: "use-cases",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-enter-a-new-market": {
    id: "use-case-enter-a-new-market",
    src: "/images/use-cases/use-case-enter-a-new-market.webp",
    alt: "Growth team charting international territory rollout and localized search visibility strategy",
    topic: "Enter a New Market",
    category: "use-cases",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-reduce-support-tickets": {
    id: "use-case-reduce-support-tickets",
    src: "/images/use-cases/use-case-reduce-support-tickets.webp",
    alt: "Support operations showing decreased ticket volume following self-service documentation rollout",
    topic: "Reduce Support Tickets",
    category: "use-cases",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-improve-data-quality": {
    id: "use-case-improve-data-quality",
    src: "/images/use-cases/use-case-improve-data-quality.webp",
    alt: "Data engineer validating schema constraints and automated data sanitization routines",
    topic: "Improve Data Quality",
    category: "use-cases",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-consolidate-business-tools": {
    id: "use-case-consolidate-business-tools",
    src: "/images/use-cases/use-case-consolidate-business-tools.webp",
    alt: "Unified digital workspace replacing fragmented SaaS subscriptions with integrated software",
    topic: "Consolidate Business Tools",
    category: "use-cases",
    type: "business",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-onboard-customers-faster": {
    id: "use-case-onboard-customers-faster",
    src: "/images/use-cases/use-case-onboard-customers-faster.webp",
    alt: "Customer success consultant leading rapid product onboarding session with new enterprise account",
    topic: "Onboard Customers Faster",
    category: "use-cases",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-scale-without-hiring": {
    id: "use-case-scale-without-hiring",
    src: "/images/use-cases/use-case-scale-without-hiring.webp",
    alt: "Compact high-leverage business team handling increasing transaction volume via automated pipelines",
    topic: "Scale Without Hiring",
    category: "use-cases",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-launch-a-digital-product": {
    id: "use-case-launch-a-digital-product",
    src: "/images/use-cases/use-case-launch-a-digital-product.webp",
    alt: "Product engineering squad celebrating successful public release of new digital web application",
    topic: "Launch a Digital Product",
    category: "use-cases",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "use-case-replace-spreadsheet-processes": {
    id: "use-case-replace-spreadsheet-processes",
    src: "/images/use-cases/use-case-replace-spreadsheet-processes.webp",
    alt: "Modern web database application structured cleanly with role-based permissions and audits",
    topic: "Replace Spreadsheet Processes",
    category: "use-cases",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "tech-web-stack": {
    id: "tech-web-stack",
    src: "/images/technologies/tech-web-stack.webp",
    alt: "Front-end engineers architecting Next.js App Router applications with static site generation",
    topic: "Web Stack",
    category: "technology",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "tech-ai-stack": {
    id: "tech-ai-stack",
    src: "/images/technologies/tech-ai-stack.webp",
    alt: "AI infrastructure and neural model inference frameworks powering production intelligence",
    topic: "AI Stack",
    category: "technology",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "tech-automation-platforms": {
    id: "tech-automation-platforms",
    src: "/images/technologies/tech-automation-platforms.webp",
    alt: "Enterprise workflow orchestration engines triggering event-driven business microservices",
    topic: "Automation Platforms",
    category: "technology",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "tech-engineering-standards": {
    id: "tech-engineering-standards",
    src: "/images/technologies/tech-engineering-standards.webp",
    alt: "Lead engineers conducting peer code review against strict type-safety and performance rules",
    topic: "Engineering Standards",
    category: "technology",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "tech-search-and-analytics": {
    id: "tech-search-and-analytics",
    src: "/images/technologies/tech-search-and-analytics.webp",
    alt: "Search retrieval algorithms and server-side log analytics monitoring indexing rates",
    topic: "Search & Analytics Stack",
    category: "technology",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "tech-integrations": {
    id: "tech-integrations",
    src: "/images/technologies/tech-integrations.webp",
    alt: "Middleware software bridging legacy relational databases with modern cloud webhook services",
    topic: "Integrations Stack",
    category: "technology",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "tech-content-platforms": {
    id: "tech-content-platforms",
    src: "/images/technologies/tech-content-platforms.webp",
    alt: "Decoupled headless content architecture distributing structured text across multiple surfaces",
    topic: "Content Platforms",
    category: "technology",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "tech-cloud-and-hosting": {
    id: "tech-cloud-and-hosting",
    src: "/images/technologies/tech-cloud-and-hosting.webp",
    alt: "DevOps specialist configuring edge caching, container deployment, and automated scaling",
    topic: "Cloud & Hosting",
    category: "technology",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "tech-data-platforms": {
    id: "tech-data-platforms",
    src: "/images/technologies/tech-data-platforms.webp",
    alt: "Structured SQL warehouse tables and ETL transformation pipelines for business intelligence",
    topic: "Data Platforms",
    category: "technology",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "tech-crm-platforms": {
    id: "tech-crm-platforms",
    src: "/images/technologies/tech-crm-platforms.webp",
    alt: "Enterprise CRM interface orchestrating multi-channel client communications and lead history",
    topic: "CRM Platforms",
    category: "technology",
    type: "process",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "tech-mobile-platforms": {
    id: "tech-mobile-platforms",
    src: "/images/technologies/tech-mobile-platforms.webp",
    alt: "Responsive viewport testing ensuring zero layout shift and touch target compliance",
    topic: "Mobile Platforms",
    category: "technology",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "tech-security-and-access": {
    id: "tech-security-and-access",
    src: "/images/technologies/tech-security-and-access.webp",
    alt: "Cybersecurity governance and identity access management protecting sensitive client data",
    topic: "Security & Access",
    category: "technology",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "tech-testing-and-quality": {
    id: "tech-testing-and-quality",
    src: "/images/technologies/tech-testing-and-quality.webp",
    alt: "Automated regression testing test harness verifying end-to-end user journeys before deployment",
    topic: "Testing & Quality",
    category: "technology",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "tech-observability": {
    id: "tech-observability",
    src: "/images/technologies/tech-observability.webp",
    alt: "Real-time system observability charts tracking server latencies, error budgets, and API response rates",
    topic: "Observability",
    category: "technology",
    type: "technology",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "tech-payments-and-billing": {
    id: "tech-payments-and-billing",
    src: "/images/technologies/tech-payments-and-billing.webp",
    alt: "PCI-compliant payment processing infrastructure handling recurring subscriptions and global invoices",
    topic: "Payments & Billing",
    category: "technology",
    type: "business",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "tech-accessibility-standards": {
    id: "tech-accessibility-standards",
    src: "/images/technologies/tech-accessibility-standards.webp",
    alt: "User testing assistive technology, high-contrast tokens, and keyboard accessibility navigation",
    topic: "Accessibility Standards",
    category: "technology",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "company-hub": {
    id: "company-hub",
    src: "/images/company/company-hub.webp",
    alt: "Technology team collaborating in open plan office workspace in Pune",
    topic: "BizzFly Company Hub",
    category: "company",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "hero",
    caption: "The BizzFly team in Pune, combining digital growth strategy with systems engineering.",
  },
  "company-about": {
    id: "company-about",
    src: "/images/company/company-about-team.webp",
    alt: "BizzFly team members collaborating in bright, modern office space in Pune, India",
    topic: "About BizzFly",
    category: "company",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "hero",
    caption: "The BizzFly team in Pune, bringing search visibility and software engineering together.",
  },
  "company-how-we-work": {
    id: "company-how-we-work",
    src: "/images/company/company-how-we-work.webp",
    alt: "Strategy and delivery leads mapping agile project milestones and technical dependencies",
    topic: "How We Work",
    category: "company",
    type: "process",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
    caption: "Transparent delivery sequences with fixed scopes and measurable commercial milestones.",
  },
  "company-approach": {
    id: "company-approach",
    src: "/images/company/company-approach-diagnosis.webp",
    alt: "Engineering and consulting partners analyzing core business constraints prior to proposing code",
    topic: "Our Approach",
    category: "company",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
    caption: "Diagnosis before prescription: establishing the real cause before proposing work.",
  },
  "company-careers": {
    id: "company-careers",
    src: "/images/company/company-careers-workplace.webp",
    alt: "Contemporary engineering and growth workspace supporting professional development and focus",
    topic: "Careers at BizzFly",
    category: "company",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
    caption: "An engineering-led culture focused on quality, accessibility, and measurable business growth.",
  },
  "company-discovery-process": {
    id: "company-discovery-process",
    src: "/images/company/company-discovery-process.webp",
    alt: "Consultants conducting an initial discovery consultation to understand customer intent and systems",
    topic: "Discovery Process",
    category: "company",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "company-working-with-us": {
    id: "company-working-with-us",
    src: "/images/company/company-working-with-us.webp",
    alt: "Collaborative partnership between client team and BizzFly technical specialists",
    topic: "Working With Us",
    category: "company",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "contact-consultation": {
    id: "contact-consultation",
    src: "/images/contact/contact-consultation-strategy.webp",
    alt: "Senior digital growth advisor conducting an introductory 30-minute discovery conversation",
    topic: "Contact Consultation",
    category: "company",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "consultation",
    caption: "Thirty minutes on the problem, not a sales pitch. We reply within one business day.",
  },
  "case-studies-standard": {
    id: "case-studies-standard",
    src: "/images/case-studies/case-studies-verified-standard.webp",
    alt: "Technical documentation and verified measurement standard governing published client outcomes",
    topic: "Case Studies Publishing Standard",
    category: "case-studies",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "hero",
    caption: "Verified metrics with measurement windows, named challenges, and written client sign-off.",
  },
  "case-studies-audit": {
    id: "case-studies-audit",
    src: "/images/case-studies/case-studies-engineering-audit.webp",
    alt: "Architects reviewing quantitative benchmark metrics before and after system implementation",
    topic: "Implementation Verification",
    category: "case-studies",
    type: "process",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "resource-ai-overviews-clicks": {
    id: "resource-ai-overviews-clicks",
    src: "/images/resources/resource-ai-overviews-clicks.webp",
    alt: "User searching on mobile device observing AI Overview summarization pushing organic links down",
    topic: "AI Overviews Impact",
    category: "resources",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "resource-redesign-traffic-loss": {
    id: "resource-redesign-traffic-loss",
    src: "/images/resources/resource-redesign-traffic-loss.webp",
    alt: "Web analytics screen displaying sudden organic traffic reduction following an unmapped website relaunch",
    topic: "Website Redesign Traffic Loss",
    category: "resources",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "resource-when-to-replatform": {
    id: "resource-when-to-replatform",
    src: "/images/resources/resource-when-to-replatform.webp",
    alt: "Engineering team evaluating CMS replatforming tradeoffs between monolithic and headless stacks",
    topic: "When to Replatform a Website",
    category: "resources",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "resource-invest-in-analytics": {
    id: "resource-invest-in-analytics",
    src: "/images/resources/resource-invest-in-analytics.webp",
    alt: "Strategists reviewing event telemetry and attribution modeling to justify analytics investment",
    topic: "When to Invest in Analytics",
    category: "resources",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "resource-outsource-development": {
    id: "resource-outsource-development",
    src: "/images/resources/resource-outsource-development.webp",
    alt: "In-house technical lead onboarding external development specialists to accelerate feature delivery",
    topic: "When to Outsource Development",
    category: "resources",
    type: "human",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "resource-guide-seo-audit": {
    id: "resource-guide-seo-audit",
    src: "/images/resources/resource-guide-seo-audit.webp",
    alt: "SEO consultant systematically auditing enterprise website crawl logs and index coverage",
    topic: "Enterprise SEO Audit Guide",
    category: "resources",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "resource-checklist-technical-seo": {
    id: "resource-checklist-technical-seo",
    src: "/images/resources/resource-checklist-technical-seo.webp",
    alt: "Technical checklist outlining crawlability, canonicals, schema data, and mobile readiness tests",
    topic: "Technical SEO Checklist",
    category: "resources",
    type: "process",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "resource-comparison-framework": {
    id: "resource-comparison-framework",
    src: "/images/resources/resource-comparison-framework.webp",
    alt: "Comparative matrix illustrating the structural differences between traditional search indexing and AI answer retrieval",
    topic: "SEO vs AEO Comparison",
    category: "resources",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "resource-decision-tree": {
    id: "resource-decision-tree",
    src: "/images/resources/resource-decision-tree.webp",
    alt: "Decision framework weighing custom internal software development against commercial SaaS licensing",
    topic: "Build vs Buy Decision Framework",
    category: "resources",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
  "resource-glossary-knowledge": {
    id: "resource-glossary-knowledge",
    src: "/images/resources/resource-glossary-knowledge.webp",
    alt: "Authoritative digital reference library and terminology definitions for digital growth and AI",
    topic: "BizzFly Reference Glossary",
    category: "resources",
    type: "editorial",
    aspectRatio: "3:2",
    width: 1200,
    height: 800,
    usage: "editorial",
  },
};

export function getImage(id: string): ImageMetadata | undefined {
  return imageRegistry[id];
}

export function requireImage(id: string): ImageMetadata {
  const img = imageRegistry[id];
  if (!img) {
    throw new Error(`[ImageRegistry] Missing registered image for ID: "${id}"`);
  }
  return img;
}

export function getAllImages(): ImageMetadata[] {
  return Object.values(imageRegistry);
}
